#!/bin/bash
alias ll='ls -lh'
alias la='ls -lA'
alias turn-off='sudo shutdown -h now'

if command -v bat &> /dev/null; then
  alias cat='bat'
fi

if command -v nvim &> /dev/null; then
  alias vim='nvim'
fi
