#!/bin/bash

# Set up oh my posh
if command -v oh-my-posh &> /dev/null; then
	eval "$(oh-my-posh init bash --config ~/.cache/oh-my-posh/themes/amro.omp.json)"
fi

# Set up fzf key bindings and fuzzy completion
if command -v fzf &> /dev/null; then
	eval "$(fzf --bash)"
fi

export XDG_DATA_DIRS="$XDG_DATA_DIRS:/var/lib/flatpak/exports/bin"
