#!/bin/bash

function __git_prompt() {
  local branch="$(git branch --show-current 2> /dev/null)"
  if [[ -n "$branch" ]]; then
    echo -e " | \001\e[96m\002$branch\001\e[0m\002"
  fi
}

function __last_command_status() {
  local rc=$1
  if [[ "$rc" != "0" ]]; then
    echo -e " | \001\e[91m\002$rc\001\e[0m\002"
  fi
}

shopt -s promptvars
PROMPT_COMMAND='LAST_STATUS=$?'
PS1='\[\e[38;5;40m\]\u@\h\[\e[0m\] | \[\e[38;5;33m\]\w\[\e[0m\]$(__git_prompt) | \T$(__last_command_status $LAST_STATUS)\n\[\e[36m\]#\[\e[0m\] '

# Set up oh my posh
# if command -v oh-my-posh &> /dev/null; then
# 	eval "$(oh-my-posh init bash --config ~/.cache/oh-my-posh/themes/amro.omp.json)"
# fi
#
